### PR TITLE
Third party plugins + no customappicons toast

### PR DESCRIPTION
**Pull request by AnikeiPS**

### CODE REVIEW

**Comment by Tolga1452** [comment]
i'm closing this because each pr should include changes about one plugin. multiple ones would cause chaos while verifying

**Comment by AnikeiPS** [comment]
okay

**Comment by AnikeiPS** [comment]
> i'm closing this because each pr should include changes about one plugin. multiple ones would cause chaos while verifying

does that mean for every plugin i should add only 1 plugin?
many prs

**Comment by Trao-X** [comment]
> > i'm closing this because each pr should include changes about one plugin. multiple ones would cause chaos while verifying
> 
> does that mean for every plugin i should add only 1 plugin? many prs

It does mean that.

**Comment by Tolga1452** [comment]
> > i'm closing this because each pr should include changes about one plugin. multiple ones would cause chaos while verifying
> 
> does that mean for every plugin i should add only 1 plugin? many prs

uhhh did you mean "for every pr" ?

**Pull request closed without merging**
