### PR TITLE
feat(plugin): Quests completer

### PR DESCRIPTION
**Pull request by happyendermangit**
This plugin completes quests without having the game. **this is useful for quests that rewards you avatar decorations**

The "Complete Quest" button is enabled only if:
- You have uncompleted quests
- You are streaming something
- Someone is watching your stream (your alt or your friend.)

For Web, this requires to install an [extension](https://github.com/SerStars/QuestCompleterExtension/tree/plugin) (only for chrome)

## Screenshots:
image
image
image

### CODE REVIEW

**Comment by Trao-X** [comment]
This is pog. 📦

**Comment by Trao-X** [comment]
Naw. 💀

**Comment by RobinRMC** [comment]
Client mods are also against Discord's ToS... :/

**Comment by Tolga1452** [comment]
> Client mods are also against Discord's ToS... :/

but this is not only client modification. it also contains api abusing

**Pull request closed without merging**
