### PR TITLE
Add BlockReplyPings Plugin

### PR DESCRIPTION
**Pull request by Grafaffel**
## Screenshot

image

### CODE REVIEW

**Comment by AnikeiPS** [comment]
you dont even have any code

**Comment by Grafaffel** [comment]
> you dont even have any code

what?

**Review by Tolga1452 — CHANGES_REQUESTED** [review]
uhh where is the plugin code :skulk:

**Comment by Grafaffel** [comment]
> uhh where is the plugin code :skulk:

wait, looks like it didn't commit

**Comment by Grafaffel** [comment]
> uhh where is the plugin code :skulk:

I am gonna commit tomorrow, because it didn't commit the first one

**Pull request closed without merging**
